name: Security Scan

on:
  push:
    branches: ["main"]

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'reports/trivy.json'

      - name: Show file content (DEBUG)
        run: |
          echo "===== FILE CONTENT ====="
          cat reports/trivy.json | head -n 20

      - name: Commit report
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reports/trivy.json
          git commit -m "Update scan report" || echo "No changes"
          git push
